image: Visual Studio 2013
environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 9
    - nodejs_version: LTS
    - nodejs_version: Current
platform:
  - x86
  - x64
cache:
  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
#  - npm install polygon-points
#  - npm cache clean --force
  - npm install
#  - npm install --cache /tmp/empty-cache
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER"
before_test:
#  - npm i -g npm
test_script:
  - node --version
  - npm --version
  - npm test
#  - npm run gray:region
on_success:
#  - npm run examples
#  - npm run jpeg
build: off