version: '{branch}-{build}'
image:
  - Visual Studio 2019
  - Ubuntu2004
  - macOS-BigSur
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  matrix:
    - nodejs_version: 14
    - nodejs_version: 16
    - nodejs_version: 18
    - nodejs_version: 20
platform:
  # - x86
  - x64
#matrix:
# fast_finish: true
# exclude:
#   - image: Ubuntu1804
#     platform: x86
#cache:
#  - node_modules
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - sh: nvm install $nodejs_version
  - npm install
#  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
#  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER"
before_test:
  - node --version
  - npm --version
test_script:
  - npm test
#on_success:
#  - npm run examples
build: off
