image:
  - Visual Studio 2017
  - Ubuntu1804
environment:
  matrix:
    - nodejs_version: 8
#    - nodejs_version: 9
#    - nodejs_version: LTS
#    - nodejs_version: Current
platform:
  - x86
  - x64
matrix:
  exclude:
    - image: Ubuntu1804
      platform: x86
cache:
  - node_modules
install:
  - cmd: powershell Install-Product node $env:nodejs_version $env:platform
  - sh: nvm install $nodejs_version
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER"
  - npm install
before_test:
#  - npm i -g npm
test_script:
  - node --version
  - npm --version
  - npm test
on_success:
#  - npm run examples
#  - npm run jpeg
build: off